//
//  ProductDetailInteractor.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/12/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol ProductDetailBusinessLogic {
    func fetchDetailInfo()
}

protocol ProductDetailDataStore {
    //var name: String { get set }
}

class ProductDetailInteractor: ProductDetailBusinessLogic, ProductDetailDataStore {
    var presenter: ProductDetailPresentationLogic?
    var worker: ProductDetailManagable? = ProductDetailWorkerStub()
    private var disposeBag: DisposeBag = .init()
    //var name: String = ""
    
    // MARK: Do something
    func fetchDetailInfo() {
        worker?.fetchProductDetailInfo(id: 1)
            .subscribe(on: ConcurrentDispatchQueueScheduler(qos: .background))
            .observe(on: MainScheduler.instance)
            .subscribe { [weak self] response in
                self?.presenter?.presentItemDetailInfo(response: response.data)
            } onError: { error in
                
            }.disposed(by: disposeBag)
    }
}
