//
//  ProductDetailModels.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/12/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

enum ProductDetail {
    // MARK: Use cases
    
    enum DetailProductItem {
        struct Request {
            var detailId: Int
        }
        struct Response: Decodable {
            var status: String
            var data: DetailProductItem.Response.Data
            
            struct Data: Decodable {
                var productImageListURL: [String]
                var profileImageURL: String
                var registerName: String
                var registerLocation: String
                var mannerTemperature: Double
                var productTitle: String
                var price: Int
                var productCategory: String
                var registedDate: Int
                var contentText: String
                var preferredLocation: String
                var similarProducts: [SimilarProduct]
            }
            
            struct SimilarProduct: Decodable {
                var productImageURL: String
                var productImageTitle: String
                var productPrice: Int
            }
        }
        
        struct ProductDetailImageViewModel: Equatable {
            static func == (
            lhs: ProductDetail.DetailProductItem.ProductDetailImageViewModel,
                rhs: ProductDetail.DetailProductItem.ProductDetailImageViewModel
            ) -> Bool {
                return lhs.id == rhs.id
            }
            
            var id: UUID
            var productDetailImage: Observable<UIImage>
            
            init(id: UUID = UUID(), productDetailImage: Observable<UIImage>) {
                self.id = id
                self.productDetailImage = productDetailImage
            }
        }
        
        struct ProductDetailInfoViewModel: Equatable {
            static func == (
                lhs: ProductDetail.DetailProductItem.ProductDetailInfoViewModel,
                rhs: ProductDetail.DetailProductItem.ProductDetailInfoViewModel
            ) -> Bool {
                return lhs.id == rhs.id
            }
            
            var id: UUID
            var productDetailImageViewModels: [ProductDetailImageViewModel]
            var profileImage: Observable<UIImage>
            var registerName: String
            var registerLocation: String
            var mannerTemperature: String
            var productTitle: String
            var price: String
            var productCategory: String
            var registedDate: String
            var contentText: String
            var preferredLocation: String
            var similarProducts: [SimilarProductViewModel]
            
            static var empty = Self.init()
            
            init(
                id: UUID = UUID(),
                productDetailImageViewModels: [ProductDetailImageViewModel],
                profileImage: Observable<UIImage>,
                registerName: String,
                registerLocation: String,
                mannerTemperature: String,
                productTitle: String,
                price: String,
                productCategory: String,
                registedDate: String,
                contentText: String,
                preferredLocation: String,
                similarProducts: [SimilarProductViewModel]
            ) {
                self.id = id
                self.productDetailImageViewModels = productDetailImageViewModels
                self.profileImage = profileImage
                self.registerName = registerName
                self.registerLocation = registerLocation
                self.mannerTemperature = mannerTemperature
                self.productTitle = productTitle
                self.price = price
                self.productCategory = productCategory
                self.registedDate = registedDate
                self.contentText = contentText
                self.preferredLocation = preferredLocation
                self.similarProducts = similarProducts
            }
            
            init() {
                self.id = UUID()
                self.productDetailImageViewModels = []
                self.profileImage = Observable.empty()
                self.registerName = ""
                self.registerLocation = ""
                self.mannerTemperature = ""
                self.productTitle = ""
                self.price = ""
                self.productCategory = ""
                self.registedDate = ""
                self.contentText = ""
                self.preferredLocation = ""
                self.similarProducts = []
            }
        }
        
        struct SimilarProductViewModel: Equatable {
            static func == (
                lhs: ProductDetail.DetailProductItem.SimilarProductViewModel,
                rhs: ProductDetail.DetailProductItem.SimilarProductViewModel
            ) -> Bool {
                return lhs.id == rhs.id
            }
            
            var id: UUID
            var productImageURL: Observable<UIImage>
            var productTitle: String
            var productPrice: String
            
            init(
                id: UUID = UUID(),
                productImageURL: Observable<UIImage>,
                productTitle: String,
                productPrice: String
            ) {
                self.id = id
                self.productImageURL = productImageURL
                self.productTitle = productTitle
                self.productPrice = productPrice
            }
        }
    }
}
