//
//  ProductDetailViewController.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/12/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FlexLayout

protocol ProductDetailDisplayLogic: AnyObject {
}

class ProductDetailViewController: UIViewController, ProductDetailDisplayLogic {
    var interactor: ProductDetailBusinessLogic?
    var router: (NSObjectProtocol & ProductDetailRoutingLogic & ProductDetailDataPassing)?
    
    // MARK: Object lifecycle
    private var rootFlexContainer: UIView = UIView()
    private var productImageListView: ProductDetailImageListView = ProductDetailImageListView()
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = ProductDetailInteractor()
        let presenter = ProductDetailPresenter()
        let router = ProductDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupViews()
    }
    
    private func setupViews() {
        view.backgroundColor = .white
        
        view.addSubview(rootFlexContainer)
        rootFlexContainer.flex
            .direction(.column)
            .define { rootFlex in
                rootFlex
                    .addItem(self.productImageListView)
            }
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        navigationController?.isNavigationBarHidden = false
        navigationController?.navigationBar.backgroundColor = .clear
        
        rootFlexContainer.pin
            .horizontally()
            .top()
            .bottom(view.pin.safeArea.bottom)
        
        rootFlexContainer.flex.layout()
    }
    
    // MARK: Do something
}
