//
//  ProductDetailViewController.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/12/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import FlexLayout
import PinLayout

protocol ProductDetailDisplayLogic: AnyObject {
    func displayItemDetailInfo(
        productInfoViewModel: ProductDetail.DetailProductItem.ProductDetailInfoViewModel
    )
}

class ProductDetailViewController: UIViewController, ProductDetailDisplayLogic {
    var interactor: ProductDetailBusinessLogic?
    var router: (NSObjectProtocol & ProductDetailRoutingLogic & ProductDetailDataPassing)?
    
    // MARK: Object lifecycle
    private var rootFlexContainer: UIView = UIView()
    private var productImageListView: ProductDetailImageListView = ProductDetailImageListView()
    
    private let likeButton: UIButton = {
        let button = UIButton(type: .system)
        button.setImage(.init(systemName: "heart"), for: .normal)
        return button
    }()
    private let chatButton: UIButton = {
        let button = UIButton(type: .system)
        button.layer.cornerRadius = 8
        button.backgroundColor = .systemOrange
        button.setTitleColor(.white, for: .normal)
        button.setTitle("채팅하기", for: .normal)
        return button
    }()
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = ProductDetailInteractor()
        let presenter = ProductDetailPresenter()
        let router = ProductDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupViews()
        interactor?.fetchDetailInfo()
    }
    
    private func setupViews() {
        view.backgroundColor = .white
        
        view.addSubview(rootFlexContainer)
        rootFlexContainer.flex
            .direction(.column)
            .define { rootFlex in
                rootFlex
                    .addItem(productImageListView)
                    .width(100%)
                    .grow(9.2)
                    .basis(0)
                
                rootFlex
                    .addItem(UIView())
                    .direction(.row)
                    .alignItems(.center)
                    .justifyContent(.center)
                    .width(100%)
                    .grow(0.8)
                    .basis(0)
                    .define { chatFlexView in
                        chatFlexView.addItem(likeButton)
                            .width(10%)
                            .aspectRatio(1)
                            .marginRight(8)
                        chatFlexView.addItem(chatButton)
                            .width(80%)
                            .height(50)
                            .padding(16)
                    }
            }
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        rootFlexContainer.pin
            .top()
            .left()
            .right()
            .bottom(view.safeAreaInsets.bottom)
        
        rootFlexContainer.flex.layout()
    }
    
    // MARK: Do something
    func displayItemDetailInfo(
        productInfoViewModel: ProductDetail.DetailProductItem.ProductDetailInfoViewModel
    ) {
        self.productImageListView.updateViewModel(productInfoViewModel)
    }
}
