//
//  ProductDetailModels.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/12/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

enum ProductDetail {
    // MARK: Use cases
    
    enum DetailProductItem {
        struct Request {
            var detailId: Int
        }
        struct Response: Decodable {
            var productImageListURL: [String]
            var profileImageURL: String
            var registerName: String
            var registerLocation: String
            var mannerTemperature: Double
            var productTitle: String
            var price: Int
            var productCategory: String
            var registedDate: Int
            var contentText: String
            var preferedLocation: String
        }
        
        struct ViewModel: Equatable {
            static func == (
                lhs: ProductDetail.DetailProductItem.ViewModel,
                rhs: ProductDetail.DetailProductItem.ViewModel
            ) -> Bool {
                return lhs.id == rhs.id
            }
            
            var id: UUID
            var productDetailImages: Observable<[UIImage]>
            var profileImage: Observable<UIImage>
            var registerName: String
            var registerLocation: String
            var mannerTemperature: String
            var productTitle: String
            var price: String
            var productCategory: String
            var registedDate: String
            var contentText: String
            var preferedLocation: String
        }
    }
}
