//
//  HomeHeaderPresenter.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/4/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeHeaderPresentationLogic {
    func presentSomething(response: HomeHeader.Something.Response)
}

class HomeHeaderPresenter: HomeHeaderPresentationLogic {
    weak var viewController: HomeHeaderDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: HomeHeader.Something.Response) {
        let viewModel = HomeHeader.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
