//
//  HomeHeaderInteractor.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/4/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeHeaderBusinessLogic {
    func doSomething(request: HomeHeader.Something.Request)
}

protocol HomeHeaderDataStore {
    //var name: String { get set }
}

class HomeHeaderInteractor: HomeHeaderBusinessLogic, HomeHeaderDataStore {
    var presenter: HomeHeaderPresentationLogic?
    var worker: HomeHeaderWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: HomeHeader.Something.Request) {
        worker = HomeHeaderWorker()
        worker?.doSomeWork()
        
        let response = HomeHeader.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
