//
//  HomeHeaderViewController.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/4/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FlexLayout
import PinLayout

protocol HomeHeaderDisplayLogic: AnyObject {
    func displaySomething(viewModel: HomeHeader.Something.ViewModel)
}

class HomeHeaderViewController: UIViewController, HomeHeaderDisplayLogic {
    var interactor: HomeHeaderBusinessLogic?
    var router: (NSObjectProtocol & HomeHeaderRoutingLogic & HomeHeaderDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = HomeHeaderInteractor()
        let presenter = HomeHeaderPresenter()
        let router = HomeHeaderRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
        self.setupViews()
    }
    
    // MARK: Do something
    
    private let myPlaceButton: UIButton = {
        let button: UIButton = UIButton(type: .system)
        button.setTitle("서원동", for: .normal)
        button.setImage(UIImage(
            systemName: "chevron.down"
        )?.resized(to: .init(width: 16, height: 8)
        ), for: .normal)
        button.setTitleColor(.black, for: .normal)
        button.titleLabel?.font = .systemFont(ofSize: 30, weight: .medium)
        button.tintColor = .black
        button.semanticContentAttribute = .forceRightToLeft
        button.titleEdgeInsets = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 8)
        return button
    }()
    
    private let notificationButton: UIButton = {
        let button: UIButton = UIButton(type: .system)
        button.setImage(UIImage(systemName: "bell"), for: .normal)
        button.tintColor = .black
        return button
    }()
    
    private let searchButton: UIButton = {
        let button: UIButton = UIButton(type: .system)
        button.setImage(UIImage(systemName: "magnifyingglass"), for: .normal)
        button.tintColor = .black
        return button
    }()
    
    private let totalMenuButton: UIButton = {
        let button: UIButton = UIButton(type: .system)
        button.setImage(UIImage(systemName: "line.3.horizontal"), for: .normal)
        button.tintColor = .black
        return button
    }()
    
    private func setupViews() {
        self.view.backgroundColor = .white
        self.view.addSubview(myPlaceButton)
        self.view.flex.direction(.row).define { flex in
            flex.justifyContent(.start)
            flex.alignItems(.center)
            
            flex.addItem(myPlaceButton)
                .marginLeft(16)
                .paddingHorizontal(10)
            
            flex.addItem().grow(1)
            
            flex.addItem(searchButton)
                .height(60%)
                .aspectRatio(1)
                .marginHorizontal(2.5)
            
            flex.addItem(notificationButton)
                .height(60%)
                .aspectRatio(1)
                .marginHorizontal(2.5)
            
            flex.addItem(totalMenuButton)
                .height(60%)
                .aspectRatio(1)
                .marginLeft(2.5)
                .marginRight(16)
        }
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        self.view.flex.layout()
    }
    
    func doSomething() {
        let request = HomeHeader.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: HomeHeader.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
