//
//  HomePresenter.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/4/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol HomePresentationLogic {
    func displayItemList(_ items: [Home.ItemList.Response.Data.Item])
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?
    private let disposeBag: DisposeBag = .init()
    
    func displayItemList(_ items: [Home.ItemList.Response.Data.Item]) {
        let imageLoader = ImageLoadManagerStub()
        
        var viewModels: [Home.ItemList.ViewModel] = []
        
        for item in items {
            let imageObserver = imageLoader.loadImage(url: item.imageUrl)
                .flatMap({ optionalImage -> Observable<UIImage> in
                    guard let image = optionalImage else {
                        return Observable.error(ImageLoadManagerStub.ErrorCase.invalidData)
                    }
                    return Observable.just(image)
                })
                .catchAndReturn(UIImage(named: "loadFailImage")!)
                .share(replay: 1, scope: .forever)
            
            let viewModel = Home.ItemList.ViewModel(
                type: item.type,
                title: item.title,
                price: item.price,
                location: item.location,
                distance: item.distance,
                registDate: timeAgoString(fromUnixTime: item.registDate),
                image: imageObserver,
                likes: item.likes,
                chatNum: item.chatNum,
                applicantNum: item.applicantNum
            )
            viewModels.append(viewModel)
        }
        viewController?.displayItemList(viewModels)
    }
    
    func timeAgoString(fromUnixTime unixTime: TimeInterval) -> String {
        let currentTime = Date().timeIntervalSince1970
        let timeDifference = abs(currentTime - unixTime)
        
        let second: TimeInterval = 1
        let minute: TimeInterval = 60 * second
        let hour: TimeInterval = 60 * minute
        let day: TimeInterval = 24 * hour
        
        if timeDifference < minute {
            let seconds = Int(timeDifference)
            return "\(seconds)초 전"
        } else if timeDifference < hour {
            let minutes = Int(timeDifference / minute)
            return "\(minutes)분 전"
        } else if timeDifference < day {
            let hours = Int(timeDifference / hour)
            return "\(hours)시간 전"
        } else {
            let days = Int(timeDifference / day)
            return "\(days)일 전"
        }
    }
}
