//
//  HomePresenter.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/4/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func displayItemList(viewModel: [Home.ItemList.ViewModel])
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?
    
    func displayItemList(viewModel: [Home.ItemList.ViewModel]) {
        //TODO: viewController에 아이템 리스트 그리라고 요청
    }
}
