//
//  HomeInteractor.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/4/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol HomeBusinessLogic {
    func fetchFirstItemList()
    func fetchNextItemList()
}

protocol HomeDataStore {
    //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?
    var worker: HomeWorkerManagable?
    
    private var myPlaceList: [String]
    private var myPlaceSelectedIndex: Int
    private var itemPageIndex: Int
    private var disposeBag: DisposeBag
    
    init() {
        worker = HomeworkerStub()
        myPlaceList = ["서원동", "개포3동"]
        myPlaceSelectedIndex = 0
        itemPageIndex = 0
        disposeBag = DisposeBag()
    }
    
    func fetchFirstItemList() {
        itemPageIndex = 0
        fetchItemList()
    }
    
    func fetchNextItemList() {
        itemPageIndex += 1
        fetchItemList()
    }
    
    private func fetchItemList() {
        worker?.fetchItemList(
            requestModel: .init(place: myPlaceList[myPlaceSelectedIndex], pageIndex: itemPageIndex)
        )
        .subscribe(on: ConcurrentDispatchQueueScheduler(qos: .background))
        .observe(on: MainScheduler.instance)
        .subscribe { [weak self] response in
            let items = response.data.items
            self?.presenter?.displayItemList(items)
        } onError: { error in
            print(error)
        }.disposed(by: disposeBag)
    }
}
