//
//  HomeViewController.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/4/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FlexLayout
import PinLayout
import KarrotListKit

protocol HomeDisplayLogic: AnyObject {
    func displayItemList(_ list: [Home.ItemList.ViewModel])
}

class HomeViewController: UIViewController, HomeDisplayLogic {
    var interactor: HomeBusinessLogic?
    var router: (NSObjectProtocol & HomeRoutingLogic & HomeDataPassing)?
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = HomeInteractor()
        let presenter = HomePresenter()
        let router = HomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setupViews()
    }
    
    // MARK: Do something
    private let homeHeaderViewController = HomeHeaderViewController()
    
    private let configuration = CollectionViewAdapterConfiguration()
    private let layoutAdapter = CollectionViewLayoutAdapter()
    
    private lazy var collectionViewAdapter = CollectionViewAdapter(
        configuration: configuration,
        collectionView: collectionView,
        layoutAdapter: layoutAdapter
    )
    
    private lazy var collectionView = UICollectionView(
      frame: .zero,
      collectionViewLayout: UICollectionViewCompositionalLayout(
        sectionProvider: layoutAdapter.sectionLayout
      )
    )
    
    private func setupViews() {
        self.navigationController?.isNavigationBarHidden = true
        
        self.addChild(homeHeaderViewController)
        if let headerView = homeHeaderViewController.view {
            self.view.addSubview(headerView)
            self.view.flex.define { flex in
                flex.direction(.column)
                    .justifyContent(.start)
                    .alignItems(.center)
                flex.addItem(headerView)
                    .width(100%)
                    .height(70)
                flex.addItem(collectionView)
                    .width(100%)
                    .grow(1)
            }
        }
        self.homeHeaderViewController.didMove(toParent: self)
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        self.view.flex.layout()
        self.homeHeaderViewController.view.pin.top(self.view.safeAreaInsets.top)
        self.collectionView.pin.below(of: self.homeHeaderViewController.view)
            .bottom(view.safeAreaInsets.bottom)
    }
    
    func fetchItemList() {
        //TODO: interactor에게 중고 물품 리스트 요청
    }
    
    func displayItemList(_ list: [Home.ItemList.ViewModel]) {
        //TODO: 화면에 표시
    }
}
