//
//  HomeModels.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/4/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

enum Home {
    enum ItemList {
        struct Request: Encodable {
            var place: String
            var pageIndex: Int
            //TODO: 서버에서 거리 계산해주면 보내고
//            var currentLocation: CLLocationCoordinate2D?
            
            init(place: String, pageIndex: Int) {
                self.place = place
                self.pageIndex = pageIndex
            }
        }
        struct Response: Decodable {
            
            var status: String
            var data: Home.ItemList.Response.Data
            
            enum ResponseError: Error {
                case invalidURL
            }
            
            struct Data: Decodable {
                var items: [Home.ItemList.Response.Data.Item]
                
                struct Item: Decodable {
                    var type: SellingType
                    var title: String
                    var price: Int
                    var location: String
                    var distance: Double
                    var registDate: Double //MARK: UNIX Time
                    var imageUrl: String
                    var likes: Int
                    var chatNum: Int? //MARK: 중고거래일 경우
                    var applicantNum: Int? //MARK: 알바 지원인 경우
                }
                
                enum SellingType: String, Decodable {
                    case sale = "sale"
                    case job = "job"
                    case advertise = "advertise"
                }
            }
        }
        
        struct ViewModel: Equatable {
            static func == (lhs: Home.ItemList.ViewModel, rhs: Home.ItemList.ViewModel) -> Bool {
                return lhs.id == rhs.id
            }
            
            var id: UUID
            var type: String
            var title: String
            var price: String
            var location: String
            var distance: String?
            var registDate: String
            var image: Observable<UIImage>
            var likes: Int
            var chatNum: Int? //MARK: 중고거래일 경우
            var applicantNum: Int?
            
            init(id: UUID = UUID(),
                 type: Home.ItemList.Response.Data.SellingType,
                 title: String,
                 price: String,
                 location: String,
                 distance: String?,
                 registDate: String,
                 image: Observable<UIImage>,
                 likes: Int,
                 chatNum: Int? = nil,
                 applicantNum: Int? = nil
            ) {
                self.id = id
                self.type = type == .job ? "알바" : type == .advertise ? "광고" : ""
                self.title = title
                self.price = price
                self.location = location
                self.distance = distance
                self.registDate = registDate
                self.image = image
                self.likes = likes
                self.chatNum = chatNum
                self.applicantNum = applicantNum
            }
        }
    }
}
