//
//  HomeInteractor.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/4/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol HomeBusinessLogic {
    func fetchItemList()
}

protocol HomeDataStore {
    //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?
    var worker: HomeWorkerManagable?
    
    private var myPlaceList: [String] = ["서원동", "개포3동"]
    private var myPlaceSelectedIndex: Int = 0
    private var itemPageIndex: Int = 0
    private var disposeBag = DisposeBag()
    
    func fetchItemList() {
        worker?.fetchItemList(
            requestModel: .init(place: myPlaceList[myPlaceSelectedIndex], pageIndex: itemPageIndex)
        )
        .observe(on: MainScheduler.instance)
        .subscribe { response in
            let viewModels = response.data.items.map {
                Home.ItemList.ViewModel.init(
                    type: $0.type,
                    title: $0.title,
                    price: $0.price,
                    location: $0.location,
                    distance: $0.distance,
                    registDate: $0.registDate,
                    imageURL: $0.imageURL,
                    likes: $0.likes
                )
            }
            self.presenter?.displayItemList(viewModel: viewModels)
        } onError: { error in
            //TODO: presenter에게 응답 값 전달, 에러 화면 표시
        }.disposed(by: disposeBag)
    }
}
