//
//  HomeViewController.swift
//  KarrotPortfolio
//
//  Created by temp_name on 12/4/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FlexLayout
import PinLayout
import KarrotListKit

protocol HomeDisplayLogic: AnyObject {
    func displayItemList(_ list: [Home.ItemList.ViewModel])
}

class HomeViewController: UIViewController, HomeDisplayLogic {
    var interactor: HomeBusinessLogic?
    var router: (NSObjectProtocol & HomeRoutingLogic & HomeDataPassing)?
    
    private let homeHeaderViewController = HomeHeaderViewController()
    private let homeItemListView: HomeItemListView = HomeItemListView()
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = HomeInteractor()
        let presenter = HomePresenter()
        let router = HomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupViews()
        homeItemListView.setDelegate(self)
    }
    
    // MARK: Do something
    
    private func setupViews() {
        navigationController?.isNavigationBarHidden = true
        
        addChild(homeHeaderViewController)
        if let headerView = homeHeaderViewController.view {
            view.addSubview(headerView)
            view.flex.define { flex in
                flex.direction(.column)
                    .justifyContent(.start)
                    .alignItems(.center)
                flex.addItem(headerView)
                    .width(100%)
                    .height(70)
                flex.addItem(homeItemListView)
                    .width(100%)
                    .grow(1)
            }
        }
        homeHeaderViewController.didMove(toParent: self)
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        view.flex.layout()
        homeHeaderViewController.view.pin.top(self.view.safeAreaInsets.top)
        homeItemListView.pin.below(of: self.homeHeaderViewController.view)
            .bottom(view.safeAreaInsets.bottom)
    }
    
    func displayItemList(_ list: [Home.ItemList.ViewModel]) {
        homeItemListView.updateViewModels(list)
    }
}

extension HomeViewController: HomeItemListViewDelegate {
    func resetViewModels() {
        interactor?.fetchFirstItemList()
    }
    
    func appendViewModels() {
        interactor?.fetchNextItemList()
    }
    
    //MARK: Routing
    func routeToDetailView() {
        router?.routeToDetailView()
    }
}
